// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEQQzxlXsvmykXtDyabgfThOplHcX8Udo',
    appId: '1:296444901875:web:a04233c460e99b4514fa86',
    messagingSenderId: '296444901875',
    projectId: 'otp-auth-890bd',
    authDomain: 'otp-auth-890bd.firebaseapp.com',
    storageBucket: 'otp-auth-890bd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-32rLtfT6rZv5gVxdHGwov9JPGiR2hsY',
    appId: '1:296444901875:android:63a2aa15cb1881c814fa86',
    messagingSenderId: '296444901875',
    projectId: 'otp-auth-890bd',
    storageBucket: 'otp-auth-890bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwaUWd0pxjmU4b2M0txdgt6zoMIMOdBFQ',
    appId: '1:296444901875:ios:654109a8d197bdb714fa86',
    messagingSenderId: '296444901875',
    projectId: 'otp-auth-890bd',
    storageBucket: 'otp-auth-890bd.appspot.com',
    androidClientId: '296444901875-dv04avi2ptk1nahku160918kiu2nbbmo.apps.googleusercontent.com',
    iosClientId: '296444901875-5v8ouk212f3tdc5s0cpr1f05tnalhd13.apps.googleusercontent.com',
    iosBundleId: 'com.example.swiftUser1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwaUWd0pxjmU4b2M0txdgt6zoMIMOdBFQ',
    appId: '1:296444901875:ios:03696e3b4daf6b5814fa86',
    messagingSenderId: '296444901875',
    projectId: 'otp-auth-890bd',
    storageBucket: 'otp-auth-890bd.appspot.com',
    androidClientId: '296444901875-dv04avi2ptk1nahku160918kiu2nbbmo.apps.googleusercontent.com',
    iosClientId: '296444901875-6sqqb9l3l93u328bo1sgsn92s7bjnh91.apps.googleusercontent.com',
    iosBundleId: 'com.example.swiftUser1.RunnerTests',
  );
}
